apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflowapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflowapp
  template:
    metadata:
      labels:
        app: workflowapp
    spec:
      containers:
      - name: workflowapp
        image: varshasawant/workflowapp:v1
        ports:
        - containerPort: 80
