name: Angular CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Angular-HelloWorld

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build -- --configuration production

    - name: Run Tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
