name: Build Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-${{ matrix.node-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}-node${{ matrix.node-version }} .
          
      - name: Verify Docker Images
        run: docker images

      - name: Save Docker Image
        run: docker save ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}-node${{ matrix.node-version }} > image-node${{ matrix.node-version }}.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
         name: docker-image
         path: image-node${{ matrix.node-version }}.tar

      
