name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_name: workflowapp
      tag: v1
    secrets: inherit

  scan:
    needs: build
    uses: ./.github/workflows/scan.yml
    with:
      image_name: workflowapp
      tag: v1
    secrets: inherit

  deploy:
   needs: scan
   uses: ./.github/workflows/deploy.yml
   with:
    image_name: workflowapp
    tag: v1
  secrets: inherit
